# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MoEReactNativeExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'MoEngage-iOS-SDK'
  # Pods for MoEReactNativeExample

  target 'MoEReactNativeExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'NotificationService' do 
  pod 'MORichNotification'
end